# Generated by Django 5.1.1 on 2024-10-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=15)),
                ('gpu', models.CharField(max_length=15)),
                ('ram', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
