# Generated by Django 5.1.1 on 2024-10-25 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_computadora_imagen_computadora_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Computadora',
        ),
    ]
